# File Description {{{
# Definitions of paths to various binaries
# required by the doPreprocessing.sh and 
# doPhotometry.sh scripts. 
#
# Typically, these files will use the instance
# of these binaries contained within you $PATH
# by setting them to <prog>=`which <prog>`.
# However, by replacing the defaults below with
# an actual /path/to/binary, that will be used
# instead
# }}}

##### 'UPDATE' Option; If we are restarting from a previously completed run #####  {{{
UPDATE='FALSE'  # can be 'TRUE' or 'FALSE'
#}}}
##### 'FORCE' Option; If we want to rewrite files that have already been reduced #####  {{{
FORCE='FALSE'  # can be 'TRUE' or 'FALSE'
#}}}

##### Choice of output data products {{{
##### 'NATV', 'UROT', 'WGTM', 'BSUB', 'ASTC'
## do you want to output 'NATiVe' detectors, 'UnROTated' detectors, 'WeiGhTMaps', 
## 'ASTrometrically Corrected', and/or 'Background SUBtracted' detectors? ##### 
## do you want to keep the RAW Pawprint (if paws are specified in a file)? 
RAWP='FALSE'  # can be 'TRUE' or 'FALSE'
NATV='FALSE'  # can be 'TRUE' or 'FALSE'
UROT='FALSE'  # can be 'TRUE' or 'FALSE'
BSUB='TRUE'  # can be 'TRUE' or 'FALSE'
WGTM='TRUE'  # can be 'TRUE' or 'FALSE'
ASTC='FALSE'  # can be 'TRUE' or 'FALSE'
#}}}

#### Details used to generate the Input Catalogue for doPreprocessing & doPhotometry {{{
# Input Catalogue is generated by running the 'compileInputCat.sh' script 
#Path to the Input Catalogues 
InputCatsPath=/vol/fohlen11/fohlen11_1/hendrik/data/KiDS/V0.5.9A/
#RA & DEC limits of the field
ralo=214
rahi=218
declo=-2
dechi=3
#}}}

#Number of Processors {{{
nproc=30
#nproc=4
#}}}

# PATHS TO REQUIRED BINARIES {{{
#Location of SourceExtractor Binary {{{
sex="/vol/software/software/astro/sextractor/bin/sex"
sex=`which sex`
#}}}

#Location of PSFEx Binary {{{
psfex="/vol/software/software/astro/psfex/psfex-3.18.0/64bit/bin/psfex"
psfex=`which psfex`
#}}}

#Location of SWarp Binary {{{
swarp="/users/awright/src/SWarp/bin/swarp"
swarp=`which swarp`
#}}}

#Location of Scamp Binary {{{
scamp=`which scamp`
#}}}

#Location of stilts Binary {{{
stilts=/vol/software/software/astro/scisoft/scisoft-7.5.0/bin/stilts
stilts="bash /net/fohlen11/home/awright/src/stilts.txt"
#}}}

#Location of the HEASoft FGauss Binary {{{
fgauss=`which fgauss`
#}}}

#Location of the HEASoft ImCopy Binary {{{
imcopy=`which imcopy`
#imcopy=/users/awright/src/imcopy
#}}}

#Location of the Rscript Binary {{{
#Rscript='/users/awright/R/bin/Rscript'
Rscript=`which Rscript`
#}}}

#Location of the R Binary {{{
#R='/users/awright/R/bin/R'
R=`which R`
#}}}
#}}}

##Catalogue to use for astrometric correction (and/or photometry); if set to "FILE", catalogue details below MUST be provided {{{
astrotype='2MASS'

##Location of Catalogue for Astrometric Correction (for doPreprocessing.sh) [optional]
##and/or for measurement of Photometry (for doPhotometry.sh) [not optional!]
# can be an ASCII (.asc) catalogue or a FITS_LDAC catalogue (ascii gets converted to LDAC). 
astrocat='ASTROCAT.asc'
apercat='ASTROCAT.csv'

##Keys for variables needed for astrometric correction & flux measurement {{{
##Catalogue Identifier 
AperType=2 #AperType: 1 = normal aperture, 2 = gaussian aperture 
CATAIDlab='SeqNr' #For CDFS & COSMOS fields: 'SeqNr'; for GAIA: 'solution_id'
## RA & DEC
RAkey='RA_THELI'            #For CDFS & COSMOS fields: 'RA_THELI'; GAIA: 'ra'
DECkey='DEC_THELI'    #For CDFS & COSMOS fields: 'DEC_THELI'; for GAIA: 'dec'
## RA & DEC Uncertainty Ellipse
RAERRkey='ERRA_WORLD_THELI' #For CDFS & COSMOS fields: 'ERRA_WORLD_THELI'; for GAIA: 'ra_error_deg'
DECERRkey='ERRB_WORLD_THELI' #For CDFS & COSMOS fields: 'ERRB_WORLD_THELI'; for GAIA: 'dec_error_deg'
THETAERRkey='ERRTHETA_WORLD_THELI' #For CDFS & COSMOS fields: 'ERRTHETA_WORLD_THELI'; for GAIA: 'DUMMY_COL'
## MAG
MAGkey='MAG_AUTO_THELI' #For CDFS & COSMOS fields: 'MAG_AUTO_THELI'; for GAIA: 'phot_g_mean_mag' 
#}}}

#Additional Aperture Parameter Keys {{{
THETAlab='THETA_J2000_THELI'
SEMIMAJORlab='Agaper_r'
SEMIMINORlab='Bgaper_r'
#}}}
#}}}

#Choice of doPreprocessing.sh output files to use in doPhotometry.sh 
imagesrc=native_bsub/   #Can be: native_bsub/, native_urot/, native_astcorr/, or convolved/ 
imageextn=bsub   #must match the above as either : bsub, urot, astcorr, or <empty> 

